# Generated by Django 5.2 on 2025-05-11 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0005_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
    ]
