# Generated by Django 5.2 on 2025-05-11 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0006_accountprofile_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountprofile',
            name='profile_image',
        ),
    ]
