# Generated by Django 5.2 on 2025-05-12 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0007_remove_accountprofile_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='price_at_add',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
