# Generated by Django 5.2 on 2025-05-12 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0009_accountprofile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountprofile',
            name='profile_picture',
            field=models.ImageField(default=1, upload_to='profile_pics/'),
            preserve_default=False,
        ),
    ]
