# Generated by Django 5.2 on 2025-05-12 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0010_alter_accountprofile_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountprofile',
            name='profile_picture',
        ),
    ]
