# Generated by Django 5.2 on 2025-05-12 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0011_remove_accountprofile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='pfp/'),
        ),
    ]
