# Generated by Django 5.2 on 2025-05-01 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0004_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
